
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://10.100.141.121:3306/weixinsp_db?useUnicode=true&amp;autoReconnect=true
#    url: jdbc:mysql://120.79.162.205:3306/spring_boot
    url: jdbc:mysql://192.168.99.63:3306/by_crm
    username: biyaodev
    password: biyao
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect