server:
  port: 8080
  servlet:
    context-path: /
#    context-path: /boot
#  springboot2.0后 使用server.servlet.context-path代替server.context-path（过时）
#  context-path: /demo


#自定义属性
cupSize: B
age: 18
content: "cupSize:${cupSize},age:${age}"

#带前缀的配置
girl:
  cupSize: B
  age: 18

# swagger2的开启状态
swagger2:
  enable: true

